blueprint:
  name: Zigbee2MQTT - Tuya Moes Smart Knob event HUE light control
  description: Automate your Tuya Smart Knob - ERS-10TZBVK-AA
  domain: automation
  input:
    switch:
      name: Tuya Smart Knob
      description: Select the action entity of the smart knob
      selector:
        entity:
          integration: mqtt
          domain: sensor
          multiple: false
    ligths:
      name: Lights to control
      description: These are the lights you want to control
      selector:
        entity:
          domain: light
          multiple: true
  source_url: https://community.home-assistant.io/t/zigbee2mqtt-tuya-moes-smart-knob-ers-10tzbvk-aa/419989
mode: restart
max_exceeded: silent
trigger:
  - platform: state
    entity_id: !input 'switch'
action:
  - variables:
      command: '{{ trigger.to_state.state }}'
  - choose:
      - conditions:
          - '{{ command == ''single'' }}'
        sequence:
          - repeat:
              for_each: !input 'lights'
              sequence:
                - service: light.turn_off
                  target:
                    entity_id: "light.{{ repeat.item }}"